java:
  aadIdentityName: pip
  ingressHost: pip-publication-services.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8081
  image: 'sdshmctspublic.azurecr.io/pip/publication-services:latest'
  keyVaults:
    pip-ss-kv:
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      secrets:
        - name: gov-uk-notify-api-key
          alias: NOTIFY_API_KEY
        - name: app-pip-publication-services-id
          alias: CLIENT_ID
        - name: app-pip-publication-services-pwd
          alias: CLIENT_SECRET
        - name: app-tenant-id
          alias: TENANT_ID
        - name: app-pip-publication-services-scope
          alias: APP_URI
        - name: app-insights-java-instrumentation-key
          alias: INSTRUMENTATION_KEY
        - name: app-pip-data-management-scope
          alias: DATA_MANAGEMENT_AZ_API
        - name: third-party-number-of-retries
          alias: NUM_OF_RETRIES
        - name: third-party-seconds-backoff
          alias: SECONDS_BACKOFF
  environment:

