java:
  aadIdentityName: pip
  ingressHost: pip-publication-services.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8081
  image: 'sdshmctspublic.azurecr.io/pip/publication-services:latest'
  keyVaults:
    pip-shared-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: pip-sharedservices-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: gov-uk-notify-api-testing-key
          alias: NOTIFY_API_TESTING_KEY
  environment:
