java:
  aadIdentityName: pip
  ingressHost: pip-publication-services.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8081
  image: 'sdshmctspublic.azurecr.io/pip/publication-services:latest'
  keyVaults:
    pip-ss-kv:
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      secrets:
        - name: gov-uk-notify-api-key
          alias: NOTIFY_API_KEY
  environment:

