name: Format terraform files

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: terraform fmt
        uses: dflook/terraform-fmt@1964140828a3cd334f311122e09f9e824060382e # v2.2.2

      - name: commit format changes to branch
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Automated Change
          commit_user_name: Terraform format GitHub Actions Bot
